name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3    
    - name: Copy .env
      run: php -r "file_exists('api-requirements/.env') || copy('api-requirements/.env.example', 'api-requiements/.env');"
    - name: Install Dependencies
      run: cd api-requirements/ && composer install --no-interaction --prefer-dist
    - name: Generate key
      run: php /home/runner/work/api-requirements/api-requirements/artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/pest
